
# Install packages
install.packages("Rcpp")
install.packages("extrafont")
install.packages("dplyr")
install.packages("dendsort", "dendextend")
install.packages("gplots")
install.packages("ggvis")
install.packages("VennDiagram")
install.packages("Hmisc")
install.packages("GeneNet")
install.packages("dbConnect")
install.packages("lars")
install.packages("grplasso")
install.packages("gglasso")
install.packages("grpreg")
install.packages("SGL")
install.packages(c("boot", "foreign", "manipulate", "MASS", "mgcv", "nlme"))
install.packages("rpart")
install.packages("randomForest")
install.packages("partykit")
install.packages("party")
install.packages("caret")
install.packages("ggplot2")
install.packages("varSelRF")
install.packages("e1071")
install.packages("glmnet")
install.packages("corrplot")
install.packages("corrgram")
install.packages("CCA")
install.packages("BioMark")
install.packages("DBI")
install.packages("fastICA")
install.packages("knitr")
install.packages("markdown")
# install.packages("mixOmics")
install.packages("plotrix")
install.packages("psych")
install.packages("RColorBrewer")
install.packages("reshape")
#install.packages("RODBC")
#install.packages("RODBCext")
install.packages("RMySQL")
install.packages("yaml")
install.packages("elasticnet")
install.packages("kernlab")
install.packages("RcppArmadillo")
install.packages("Matrix")
install.packages("knitcitations")
install.packages("bibtex")
install.packages("htmltools")
install.packages("rmarkdown")
install.packages("pander")
install.packages("outliers")
install.packages("multcomp")
install.packages("DAAG")
install.packages("leaps")
install.packages("faraway")
install.packages("WGCNA")
install.packages("plyr")
install.packages("lattice")
install.packages("stringi")
install.packages("cluster")
install.packages("nnet")
install.packages("moments")
install.packages("cwhmisc")
install.packages("RSQLServer")
install.packages("naturalsort")
install.packages("missForest")
install.packages("DT")
install.packages("colorRamps")
install.packages("MetNorm", "ruv", "metabolomics")
install.packages("shinyjs", "devtools", "curl")
install.packages("FactoMineR", "Factoshiny")
install.packages("ff")
install.packages("doMC", repos="http://R-Forge.R-project.org")
install.packages("pheatmap")

# Install Bioconductor packages
source("http://bioconductor.org/biocLite.R")
biocLite("pcaMethods")
biocLite("edgeR")
biocLite("DESeq2")
biocLite("Rsamtools")
biocLite("MLSeq")
biocLite("biomaRt")
biocLite("goseq")
biocLite("multtest")
biocLite("impute")
biocLite("preprocessCore")
biocLite("S4Vectors")
biocLite("IRanges")
biocLite("survival")
biocLite("vsn")
biocLite("topGO")
biocLite("ALL")
biocLite("hgu95av2.db")
biocLite("mgsa")
biocLite("RUVSeq")

# Install Non-R packages on linux
# r-cran-rjava 
# r-cran-dbi